window.chordPresets = [
  { name: 'Power Chord', symbol: '', category: 'diadic', textColor: 'black', backgroundColor: 'white', secondVoice: '3/2', thirdVoice: '1/1', fourthVoice: '1/1'  },
  { name: 'Shimmer Chord', symbol: '', category: 'diadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 0.25/12)', thirdVoice: '1/1', fourthVoice: '1/1'  },

  { name: 'Diminished Triad', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 6/12)', fourthVoice: '1/1' },
  { name: 'Tiny Triad', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2.50/12)', thirdVoice: 'Math.pow(2, 6/12)', fourthVoice: '1/1' },
  { name: 'Locrian Triad', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1/12)', thirdVoice: 'Math.pow(2, 6/12)', fourthVoice: '1/1' },
  { name: 'Phrygian Triad', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Inframinor Triad', symbol: 'FIN', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2.25/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Subminor Triad', symbol: 'SIN', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2.5/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Pythagorean-Minor', symbol: 'i', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: '32/27', thirdVoice: '3/2', fourthVoice: '1/1' },
  { name: 'Just-Minor', symbol: 'i', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: '6/5', thirdVoice: '3/2', fourthVoice: '1/1' },
  { name: 'Minor Triad', symbol: 'i', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Supraminor', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3.25/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Neutral Triad', symbol: '|', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3.5/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Submajor Triad', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3.75/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Major Triad', symbol: 'I', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Just-Major', symbol: 'I', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: '5/4', thirdVoice: '3/2', fourthVoice: '1/1' },
  { name: 'Pythagorean-Major', symbol: 'I', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: '81/64', thirdVoice: '3/2', fourthVoice: '1/1' },
  { name: 'Supermajor Triad', symbol: 'SAJ', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4.5/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Ultramajor Triad', symbol: 'UAJ', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4.75/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Magic Third', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3.75/12)', thirdVoice: 'Math.pow(2, 6.75/12)', fourthVoice: '1/1' },
  { name: 'Giant Triad', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4.50/12)', thirdVoice: 'Math.pow(2, 7.5/12)', fourthVoice: '1/1' },
  { name: 'Augmented Chord', symbol: 'I+', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4/12)', thirdVoice: 'Math.pow(2, 8/12)', fourthVoice: '1/1' },
  { name: 'Suspended 2', symbol: 'Sus2', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Suspended 4', symbol: 'Sus4', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 5/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },
  { name: 'Lydian Triad', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 6/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: '1/1' },

  { name: 'Diminished Chord', symbol: 'io7', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 6/12)', fourthVoice: 'Math.pow(2, 9/12)' },
  { name: 'Half-diminished Seventh', symbol: 'iø7', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 6/12)', fourthVoice: 'Math.pow(2, 10/12)' },
  { name: 'Minor Seventh', symbol: 'i7', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 10/12)' },
  { name: 'Neutral Seventh', symbol: '', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2.5/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 10.5/12)' },
  { name: 'Minor-Major Seventh', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 11/12)' },
  { name: 'Dominant Seventh', symbol: 'V7', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 10/12)' },
  { name: 'Dominant sharp-5', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4/12)', thirdVoice: 'Math.pow(2, 8/12)', fourthVoice: 'Math.pow(2, 10/12)' },
  { name: 'Harmonic Seventh', symbol: 'H7', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: '5/4', thirdVoice: '3/2', fourthVoice: '7/4' },
  { name: 'Major Seventh', symbol: 'I7', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 11/12)' },

  { name: 'Suspended 4/2', symbol: 'Sus4/2', category: 'triadic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2/12)', thirdVoice: 'Math.pow(2, 5/12)', fourthVoice: 'Math.pow(2, 7/12)' },

  { name: '? Sixth', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 11/12)' },
  { name: 'Minor Sixth', symbol: 'm6', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 9/12)' },
  { name: '? Sixth', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 8/12)' },
  { name: 'Major Sixth', symbol: 'M6', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4/12)', thirdVoice: 'Math.pow(2, 7/12)', fourthVoice: 'Math.pow(2, 9/12)' },

  { name: 'Quartal Chord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: '4/3', thirdVoice: '16/9', fourthVoice: '64/27' },
  { name: 'Quintal Chord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: '3/2', thirdVoice: '9/4', fourthVoice: '27/8' },

  { name: 'Locrian Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1/12)', thirdVoice: 'Math.pow(2, 3/12)', fourthVoice: 'Math.pow(2, 4/12)' },
  { name: 'Phrygian Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1/12)', thirdVoice: 'Math.pow(2, 3/12)', fourthVoice: 'Math.pow(2, 5/12)' },
  { name: 'Aeolian Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2/12)', thirdVoice: 'Math.pow(2, 3/12)', fourthVoice: 'Math.pow(2, 5/12)' },
  { name: 'Ionian Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2/12)', thirdVoice: 'Math.pow(2, 4/12)', fourthVoice: 'Math.pow(2, 5/12)' },
  { name: 'Lydian Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1/12)', thirdVoice: 'Math.pow(2, 3/12)', fourthVoice: 'Math.pow(2, 4/12)' },
  { name: 'Harmonic Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1/12)', thirdVoice: 'Math.pow(2, 4/12)', fourthVoice: 'Math.pow(2, 5/12)' },
  { name: '? Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2/12)', thirdVoice: 'Math.pow(2, 3/12)', fourthVoice: 'Math.pow(2, 6/12)' },
  { name: 'Lydian#9 Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 4/12)', fourthVoice: 'Math.pow(2, 6/12)' },
  { name: 'Blues Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 5/12)', fourthVoice: 'Math.pow(2, 6/12)' },
  { name: 'Bayati Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1.5/12)', thirdVoice: 'Math.pow(2, 3/12)', fourthVoice: 'Math.pow(2, 5/12)' },
  { name: 'Saba Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1.5/12)', thirdVoice: 'Math.pow(2, 3/12)', fourthVoice: 'Math.pow(2, 4/12)' },
  { name: 'Rast Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2/12)', thirdVoice: 'Math.pow(2, 3.5/12)', fourthVoice: 'Math.pow(2, 5/12)' },
  { name: 'Hijaz Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1.5/12)', thirdVoice: 'Math.pow(2, 4/12)', fourthVoice: 'Math.pow(2, 5/12)' },
  { name: 'Sakura Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 1/12)', thirdVoice: 'Math.pow(2, 5/12)', fourthVoice: 'Math.pow(2, 7/12)' },
  { name: '? Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 2/12)', thirdVoice: 'Math.pow(2, 5/12)', fourthVoice: 'Math.pow(2, 7/12)' },
  { name: 'Kumoijoshi Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 3/12)', thirdVoice: 'Math.pow(2, 5/12)', fourthVoice: 'Math.pow(2, 7/12)' },
  { name: '? Tetrachord', symbol: '', category: 'tetradic', textColor: 'black', backgroundColor: 'white', secondVoice: 'Math.pow(2, 4/12)', thirdVoice: 'Math.pow(2, 5/12)', fourthVoice: 'Math.pow(2, 7/12)' },
];
