window.pitchPresets = [
  { name: 'C4', label: 'C-natural',hz: 261.63, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'D4', label: 'D-natural', hz: 293.66, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'E4', label: 'E-natural', hz: 329.63, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'F4', label: 'F-natural', hz: 349.23, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'G4', label: 'G-natural', hz: 392.00, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'A4', label: 'A-natural', hz: 440.00, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'B4', label: 'B-natural', hz: 493.88, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },

  { name: 'C♯4/D♭4', label: 'C-sharp/D-flat', hz: 277.18, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'D♯4/E♭4', label: 'D-sharp/E-flat', hz: 311.13, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'F♯4/G♭4', label: 'F-sharp/G-flat', hz: 369.99, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'G♯4/A♭4', label: 'G-sharp/A-flat', hz: 415.30, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'A♯4/B♭4', label: 'A-sharp/B-flat', hz: 466.16, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },

  { name: 'Dd4', label: 'C-sesquasharp/D-halflat', hz: 285.30, category: 'neutral', textColor: 'cyan', backgroundColor: 'red' },
  { name: 'Ed4', label: 'D-sesquasharp/E-halflat', hz: 320.24, category: 'neutral', textColor: 'cyan', backgroundColor: 'red' },
  { name: 'F+4', label: 'F-halfsharp/G-sesquaflat', hz: 359.46, category: 'neutral', textColor: 'blue', backgroundColor: 'red' },
  { name: 'Gd4', label: 'F-sesquasharp/G-halflat', hz: 380.84, category: 'neutral', textColor: 'cyan', backgroundColor: 'red' },
  { name: 'Ad4', label: 'G-sesquasharp/A-halflat', hz: 427.47, category: 'neutral', textColor: 'cyan', backgroundColor: 'red' },
  { name: 'Bd4', label: 'A-sesquasharp/B-halflat', hz: 479.82, category: 'neutral', textColor: 'cyan', backgroundColor: 'red' },

  { name: 'E+4/Fd4', label: 'E-halfsharp/F-halflat', hz: 339.29, category: 'quarter-tone', textColor: 'orange', backgroundColor: 'cyan' },
  { name: 'B+4/Cd4', label: 'B-halfsharp/C-halflat', hz: 508.36, category: 'quarter-tone', textColor: 'orange', backgroundColor: 'cyan' },
  { name: 'C4+', label: 'C-halfsharp/D-sesquaflat', hz: 269.29, category: 'quarter-tone', textColor: 'red', backgroundColor: 'cyan' },
  { name: 'D+4', label: 'D-halfsharp/E-sesquaflat', hz: 302.27, category: 'quarter-tone', textColor: 'red', backgroundColor: 'cyan' },
  { name: 'G+4', label: 'G-halfsharp/A-sesquaflat', hz: 403.48, category: 'quarter-tone', textColor: 'red', backgroundColor: 'cyan' },
  { name: 'A+4', label: 'A-halfsharp/B-sesquaflat', hz: 452.89, category: 'quarter-tone', textColor: 'red', backgroundColor: 'cyan' },

  { name: '^C4', label: 'C-quartersharp', hz: 265.44, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^C#4/^Db4', label: '', hz: 281.22, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^D4', label: 'D-quartersharp', hz: 297.94, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^D#4/^Eb4', label: '', hz: 315.66, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^E4', label: 'E-quartersharp', hz: 334.43, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^F4', label: 'F-quartersharp', hz: 354.31, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^F#4/^Gb4', label: '', hz: 375.38, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^G4', label: 'G-quartersharp', hz: 397.70, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^G#4/^Ab4', label: '', hz: 421.35, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^A4', label: 'A-quartersharp', hz: 446.41, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^A#4/^Bb4', label: '', hz: 472.95, category: '?', textColor: 'magenta', backgroundColor: 'green' },
  { name: '^B4', label: 'B-quartersharp', hz: 501.08, category: '?', textColor: 'magenta', backgroundColor: 'green' },

  { name: 'vC#4/vDb4', label: '', hz: 273.21, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vD4', label: '-quarterflat', hz: 289.46, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vD#4/vEb4', label: '', hz: 306.67, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vE4', label: 'E-quarterflat', hz: 324.91, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vF4', label: 'F-quarterflat', hz: 344.23, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vF#4/vGb4', label: '', hz: 364.70, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vG4', label: 'G-quarterflat', hz: 386.38, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vG#4/vAb4', label: '', hz: 409.36, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vA4', label: 'A-quarterflat', hz: 433.70, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vA#4/vBb4', label: '', hz: 459.49, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vB4', label: 'B-quarterflat', hz: 486.81, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  { name: 'vC4', label: 'C-quarterflat', hz: 515.76, category: '?', textColor: 'green', backgroundColor: 'magenta' },
  
];
