window.pitchPresets = [
  { name: 'C4', label: 'C-natural', hz: 261.63, cents: 0, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'D4', label: 'D-natural', hz: 293.66, cents: 200, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'E4', label: 'E-natural', hz: 329.63, cents: 400, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'F4', label: 'F-natural', hz: 349.23, cents: 500, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'G4', label: 'G-natural', hz: 392.00, cents: 700, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'A4', label: 'A-natural', hz: 440.00, cents: 900, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'B4', label: 'B-natural', hz: 493.88, cents: 1100, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },

  { name: 'C♯4/D♭4', label: 'C-sharp/D-flat', hz: 277.18, cents: 100, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'D♯4/E♭4', label: 'D-sharp/E-flat', hz: 311.13, cents: 300, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'F♯4/G♭4', label: 'F-sharp/G-flat', hz: 369.99, cents: 600, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'G♯4/A♭4', label: 'G-sharp/A-flat', hz: 415.30, cents: 800, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'A♯4/B♭4', label: 'A-sharp/B-flat', hz: 466.16, cents: 1000, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },

  { name: 'Dd4', label: 'C-sesquisharp/D-halflat', hz: 285.30, cents: 150, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'Ed4', label: 'D-sesquisharp/E-halflat', hz: 320.24, cents: 350, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'F+4', label: 'F-halfsharp/G-sesquiflat', hz: 359.46, cents: 550, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'Gd4', label: 'F-sesquisharp/G-halflat', hz: 380.84, cents: 650, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'Ad4', label: 'G-sesquisharp/A-halflat', hz: 427.47, cents: 850, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'Bd4', label: 'A-sesquisharp/B-halflat', hz: 479.82, cents: 1050, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },

  { name: 'C4+', label: 'C-halfsharp/D-sesquiflat', hz: 269.29, cents: 50, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'D+4', label: 'D-halfsharp/E-sesquiflat', hz: 302.27, cents: 250, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'E+4/Fd4', label: 'E-halfsharp/F-halflat', hz: 339.29, cents: 450, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'G+4', label: 'G-halfsharp/A-sesquiflat', hz: 403.48, cents: 750, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'A+4', label: 'A-halfsharp/B-sesquiflat', hz: 452.89, cents: 950, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'B+4/Cd4', label: 'B-halfsharp/C-halflat', hz: 508.36, cents: 1150, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },

  { name: 'vC#4/vDb4', label: '', hz: 273.21, cents: 75, category: 'eighthtone-16EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^D4', label: 'D-quartersharp', hz: 297.94, cents: 225, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vE4', label: 'E-quarterflat', hz: 324.91, cents: 375, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^F4', label: 'F-quartersharp', hz: 354.31, cents: 525, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vG4', label: 'G-quarterflat', hz: 386.38, cents: 675, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^G#4/^Ab4', label: '', hz: 421.35, cents: 825, category: 'eighthtone-16EDO', textColor: 'black', backgroundColor: 'green' },
  { name: 'vA#4/vBb4', label: '', hz: 459.49, cents: 975, category: 'eighthtone-16EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^B4', label: 'B-quartersharp', hz: 501.08, cents: 1125, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },

  { name: '^C4', label: 'C-quartersharp', hz: 265.44, cents: 25, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^C#4/^Db4', label: '', hz: 281.22, cents: 125, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: 'vD4', label: 'D-quarterflat', hz: 289.46, cents: 175, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vD#4/vEb4', label: '', hz: 306.67, cents: 275, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^D#4/^Eb4', label: '', hz: 315.66, cents: 325, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^E4', label: 'E-quartersharp', hz: 334.43, cents: 425, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vF4', label: 'F-quarterflat', hz: 344.23, cents: 475, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vF#4/vGb4', label: '', hz: 364.70, cents: 575, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^F#4/^Gb4', label: '', hz: 375.38, cents: 625, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^G4', label: 'G-quartersharp', hz: 397.70, cents: 725, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vG#4/vAb4', label: '', hz: 409.36, cents: 775, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: 'vA4', label: 'A-quarterflat', hz: 433.70, cents: 875, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^A4', label: 'A-quartersharp', hz: 446.41, cents: 925, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^A#4/^Bb4', label: '', hz: 472.95, cents: 1025, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: 'vB4', label: 'B-quarterflat', hz: 486.81, cents: 1075, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vC4', label: 'C-quarterflat', hz: 515.76, cents: 1175, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },

  { name: '/D4', label: '', hz: 300.53, cents: 240, category: 'diesis-5EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\F4', label: '', hz: 345.22, cents: 480, category: 'diesis-5EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '/G4', label: '', hz: 396.56, cents: 720, category: 'diesis-5EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\A#4', label: '', hz: 455.52, cents: 960, category: 'diesis-5EDO', textColor: 'black', backgroundColor: 'blue' },
  
  { name: '/Db4', label: '', hz: 280.41, cents: 120, category: 'diesis-10EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\E4', label: '', hz: 322.10, cents: 360, category: 'diesis-10EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '/Ab4', label: '', hz: 425.02, cents: 840, category: 'diesis-10EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\B4', label: '', hz: 487.72, cents: 1080, category: 'diesis-10EDO', textColor: 'white', backgroundColor: 'blue' },

  { name: '\\C#4', label: '', hz: 274.00, cents: 80, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\D4', label: '', hz: 286.96, cents: 160, category: 'diesis-15EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '/Eb4', label: '', hz: 314.75, cents: 320, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\F#4', label: '', hz: 361.55, cents: 560, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '/Gb4', label: '', hz: 378.65, cents: 640, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\A4', label: '', hz: 434.95, cents: 880, category: 'diesis-15EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '/Bb4', label: '', hz: 476.58, cents: 1040, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '/B4', label: '', hz: 499.11, cents: 1120, category: 'diesis-15EDO', textColor: 'white', backgroundColor: 'blue' },

  { name: '/C4', label: '', hz: 267.75, cents: 40, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\D#4', label: '', hz: 307.56, cents: 280, category: 'diesis-30EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '/E4', label: '', hz: 337.34, cents: 440, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '/F4', label: '', hz: 353.29, cents: 520, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\G4', label: '', hz: 387.50, cents: 680, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\G#4', label: '', hz: 405.83, cents: 760, category: 'diesis-30EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '/A4', label: '', hz: 445.12, cents: 920, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\C4', label: '', hz: 510.78, cents: 1160, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },

  { name: '', label: '', hz: 288.86, cents: 171.43, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 318.93, cents: 342.86, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 352.13, cents: 514.29, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 388.78, cents: 685.71, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 429.25, cents: 857.14, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 473.93, cents: 1028.57, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },

  { name: '', label: 'C-hexaseptisharp', hz: 274.91, cents: 85.71, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 303.52, cents: 257.14, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 335.12, cents: 428.57, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 408.51, cents: 771.43, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 451.04, cents: 942.86, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 497.98, cents: 1114.29, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },

  { name: '', label: 'C-tetraseptisharp', hz: 270.41, cents: 57.14, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 279.48, cents: 114.29, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 298.56, cents: 228.57, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 308.58, cents: 285.71, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 340.69, cents: 457.14, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 363.94, cents: 571.43, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 376.16, cents: 628.57, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 401.83, cents: 742.86, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 443.65, cents: 914.29, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 458.54, cents: 971.43, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 489.83, cents: 1085.71, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 506.27, cents: 1142.86, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },

  { name: '', label: 'C-diseptisharp', hz: 265.98, cents: 28.57, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 284.13, cents: 142.86, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 313.71, cents: 314.29, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 324.24, cents: 371.43, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 346.36, cents: 485.71, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 357.99, cents: 542.86, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 382.42, cents: 657.14, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 395.25, cents: 714.29, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 422.22, cents: 828.57, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 436.39, cents: 885.71, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 481.82, cents: 1057.14, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 514.70, cents: 1171.43, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  
  { name: 'C#*4', label: '', hz: 282.52, cents: 133, category: 'Limman-9EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'D*4', label: 'D-thirdflat', hz: 305.08, cents: 266, category: 'Limman-9EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'F*4', label: 'F-thirdsharp', hz: 355.95, cents: 533, category: 'Limman-9EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Gb*4', label: '', hz: 384.38, cents: 666, category: 'Limman-9EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'A*4', label: 'A-thirdsharp', hz: 448.48, cents: 933, category: 'Limman-9EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Bb*4', label: '', hz: 484.29, cents: 1066, category: 'Limman-9EDO', textColor: 'black', backgroundColor: 'orange' },

  { name: 'C*4', label: 'C-thirdflat', hz: 271.80, cents: 66, category: 'Limman-18EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'D#*4', label: '', hz: 317.12, cents: 333, category: 'Limman-18EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'E*4', label: 'E-thirdflat', hz: 342.44, cents: 466, category: 'Limman-18EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'G*4', label: 'G-thirdsharp', hz: 399.55, cents: 733, category: 'Limman-18EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Ab*4', label: '', hz: 431.45, cents: 866, category: 'Limman-18EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'B*4', label: 'B-thirdsharp', hz: 503.40, cents: 1133, category: 'Limman-18EDO', textColor: 'white', backgroundColor: 'orange' },

  { name: 'C*4', label: 'C-thirdsharp', hz: 266.66, cents: 33, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Db*4', label: '', hz: 287.96, cents: 166, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'D*4', label: 'D-thirdsharp', hz: 299.32, cents: 233, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Eb*4', label: '', hz: 323.22, cents: 366, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'E*4', label: 'E-thirdsharp', hz: 335.98, cents: 433, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'F*4', label: 'F-thirdflat', hz: 362.80, cents: 566, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'F#*4', label: '', hz: 377.12, cents: 633, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'G*4', label: 'G-thirdflat', hz: 407.23, cents: 766, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'G#*4', label: '', hz: 423.30, cents: 833, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'A*4', label: 'A-thirdflat', hz: 457.11, cents: 966, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'A#*4', label: '', hz: 475.12, cents: 1033, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'B*4', label: 'B-thirdflat', hz: 513.08, cents: 1166, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
];
