window.pitchPresets = [
  { name: 'C♮4', label: 'C-natural', hz: 261.63, cents: 0, degrees: 0, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'D♮4', label: 'D-natural', hz: 293.66, cents: 200, degrees: 60, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'E♮4', label: 'E-natural', hz: 329.63, cents: 400, degrees: 120, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'F♮4', label: 'F-natural', hz: 349.23, cents: 500, degrees: 330, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'G♮4', label: 'G-natural', hz: 392.00, cents: 700, degrees: 30, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'A♮4', label: 'A-natural', hz: 440.00, cents: 900, degrees: 90, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },
  { name: 'B♮4', label: 'B-natural', hz: 493.88, cents: 1100, degrees: 150, category: 'diatonic', textColor: 'black', backgroundColor: 'white' },

  { name: 'C♯4/D♭4', label: 'C-sharp/D-flat', hz: 277.18, degrees: 210, cents: 100, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'D♯4/E♭4', label: 'D-sharp/E-flat', hz: 311.13, degrees: 270, cents: 300, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'F♯4/G♭4', label: 'F-sharp/G-flat', hz: 369.99, degrees: 180, cents: 600, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'G♯4/A♭4', label: 'G-sharp/A-flat', hz: 415.30, degrees: 240, cents: 800, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },
  { name: 'A♯4/B♭4', label: 'A-sharp/B-flat', hz: 466.16, degrees: 300, cents: 1000, category: 'chromatic', textColor: 'white', backgroundColor: 'black' },

  { name: 'Dd4', label: 'C-sesquisharp/D-halflat', hz: 285.30, cents: 150, degrees: 315, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'Ed4', label: 'D-sesquisharp/E-halflat', hz: 320.24, cents: 350, degrees: 15, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'F+4', label: 'F-halfsharp/G-sesquiflat', hz: 359.46, cents: 550, degrees: 75, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'Gd4', label: 'F-sesquisharp/G-halflat', hz: 380.84, cents: 650, degrees: 285, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'Ad4', label: 'G-sesquisharp/A-halflat', hz: 427.47, cents: 850, degrees: 345, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },
  { name: 'Bd4', label: 'A-sesquisharp/B-halflat', hz: 479.82, cents: 1050, degrees: 45, category: 'neutral', textColor: 'grey', backgroundColor: 'red' },

  { name: 'C4+', label: 'C-halfsharp/D-sesquiflat', hz: 269.29, cents: 50, degrees: 105, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'D+4', label: 'D-halfsharp/E-sesquiflat', hz: 302.27, cents: 250, degrees: 165, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'E+4/Fd4', label: 'E-halfsharp/F-halflat', hz: 339.29, cents: 450, degrees: 225, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'G+4', label: 'G-halfsharp/A-sesquiflat', hz: 403.48, cents: 750, degrees: 135, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'A+4', label: 'A-halfsharp/B-sesquiflat', hz: 452.89, cents: 950, degrees: 195, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },
  { name: 'B+4/Cd4', label: 'B-halfsharp/C-halflat', hz: 508.36, cents: 1150, degrees: 255, category: 'quarter-tone', textColor: 'grey', backgroundColor: 'cyan' },

  { name: 'vC#4/vDb4', label: '', hz: 273.21, cents: 75, degrees: 157.5, category: 'eighthtone-16EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^D4', label: 'D-quartersharp', hz: 297.94, cents: 225, degrees: 112.5, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vE4', label: 'E-quarterflat', hz: 324.91, cents: 375, degrees: 67.5, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^F4', label: 'F-quartersharp', hz: 354.31, cents: 525, degrees: 22.5, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vG4', label: 'G-quarterflat', hz: 386.38, cents: 675, degrees: 337.5, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^G#4/^Ab4', label: '', hz: 421.35, cents: 825, degrees: 292.5, category: 'eighthtone-16EDO', textColor: 'black', backgroundColor: 'green' },
  { name: 'vA#4/vBb4', label: '', hz: 459.49, cents: 975, degrees: 247.5, category: 'eighthtone-16EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^B4', label: 'B-quartersharp', hz: 501.08, cents: 1125, degrees: 202.5, category: 'eighthtone-16EDO', textColor: 'white', backgroundColor: 'green' },

  { name: 'C+v4', label: '', hz: 267.36, cents: 37.5, degrees: 78.75, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Db^4', label: '', hz: 279.20, cents: 112.5, degrees: 236.25, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'D♮v4', label: '', hz: 291.56, cents: 187.5, degrees: 33.75, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'D+^4', label: '', hz: 304.47, cents: 262.5, degrees: 191.25, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Edv4', label: '', hz: 317.95, cents: 337.5, degrees: 348.75, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'E♮^4', label: '', hz: 332.02, cents: 412.5, degrees: 146.25, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'E#v4', label: '', hz: 346.72, cents: 487.5, degrees: 303.75, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'F+^4', label: '', hz: 362.07, cents: 562.5, degrees: 101.25, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Gdv4', label: '', hz: 378.10, cents: 637.5, degrees: 258.75, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'G♮^4', label: '', hz: 394.84, cents: 712.5, degrees: 56.25, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'G#v4', label: '', hz: 412.32, cents: 787.5, degrees: 213.75, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Ad^4', label: '', hz: 430.58, cents: 862.5, degrees: 11.25, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'A+v4', label: '', hz: 449.64, cents: 937.5, degrees: 168.75, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Bb^4', label: '', hz: 469.55, cents: 1012.5, degrees: 326.25, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'B♮v4', label: '', hz: 490.34, cents: 1087.5, degrees: 123.75, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'B+^4/Cd^4', label: '', hz: 512.05, cents: 1162.5, degrees: 281.25, category: 'sixteenthtone-32EDO', textColor: 'white', backgroundColor: 'magenta' },
  
  { name: '^C4', label: 'C-quartersharp', hz: 265.44, cents: 25, degrees: 52.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^C#4/^Db4', label: '', hz: 281.22, cents: 125, degrees: 262.5, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: 'vD4', label: 'D-quarterflat', hz: 289.46, cents: 175, degrees: 7.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vD#4/vEb4', label: '', hz: 306.67, cents: 275, degrees: 217.5, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^D#4/^Eb4', label: '', hz: 315.66, cents: 325, degrees: 322.5, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^E4', label: 'E-quartersharp', hz: 334.43, cents: 425, degrees: 172.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vF4', label: 'F-quarterflat', hz: 344.23, cents: 475, degrees: 277.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vF#4/vGb4', label: '', hz: 364.70, cents: 575, degrees: 127.5, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^F#4/^Gb4', label: '', hz: 375.38, cents: 625, degrees: 232.5, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: '^G4', label: 'G-quartersharp', hz: 397.70, cents: 725, degrees: 82.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vG#4/vAb4', label: '', hz: 409.36, cents: 775, degrees: 187.5, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: 'vA4', label: 'A-quarterflat', hz: 433.70, cents: 875, degrees: 37.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^A4', label: 'A-quartersharp', hz: 446.41, cents: 925, degrees: 142.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: '^A#4/^Bb4', label: '', hz: 472.95, cents: 1025, degrees: 352.5, category: 'eighthtone-48EDO', textColor: 'black', backgroundColor: 'green' },
  { name: 'vB4', label: 'B-quarterflat', hz: 486.81, cents: 1075, degrees: 97.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },
  { name: 'vC4', label: 'C-quarterflat', hz: 515.76, cents: 1175, degrees: 307.5, category: 'eighthtone-48EDO', textColor: 'white', backgroundColor: 'green' },

  { name: 'C♮^4', label: '', hz: 263.53, cents: 12.5, degrees: 26.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'C+^4', label: '', hz: 271.25, cents: 62.5, degrees: 131.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'C#v4', label: '', hz: 275.19, cents: 87.5, degrees: 183.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Ddv4', label: '', hz: 283.26, cents: 137.5, degrees: 288.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Dd^4', label: '', hz: 287.38, cents: 162.5, degrees: 341.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'D♮^4', label: '', hz: 295.80, cents: 212.5, degrees: 86.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'D+v4', label: '', hz: 300.10, cents: 237.5, degrees: 138.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'D#v4', label: '', hz: 308.39, cents: 287.5, degrees: 243.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Eb^4', label: '', hz: 312.5, cents: 312.5, degrees: 296.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Ed^4', label: '', hz: 322.57, cents: 362.5, degrees: 41.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'E♮v4', label: '', hz: 327.26, cents: 387.5, degrees: 93.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'E+v4', label: '', hz: 336.85, cents: 437.5, degrees: 198.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'E+^4', label: '', hz: 341.75, cents: 462.5, degrees: 251.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'F♮^4', label: '', hz: 351.76, cents: 512.5, degrees: 356.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'F+v4', label: '', hz: 356.88, cents: 537.5, degrees: 48.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'F#v4', label: '', hz: 367.34, cents: 587.5, degrees: 153.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Gb^4', label: '', hz: 372.68, cents: 612.5, degrees: 206.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Gd^4', label: '', hz: 383.60, cents: 662.5, degrees: 311.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'G♮v4', label: '', hz: 389.18, cents: 687.5, degrees: 3.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'G+v4', label: '', hz: 400.59, cents: 737.5, degrees: 108.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'G+^4', label: '', hz: 406.61, cents: 762.5, degrees: 161.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Ab^4', label: '', hz: 418.32, cents: 812.5, degrees: 266.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Adv4', label: '', hz: 424.41, cents: 837.5, degrees: 318.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'A♮v4', label: '', hz: 436.84, cents: 887.5, degrees: 63.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'A♮^4', label: '', hz: 443.20, cents: 912.5, degrees: 116.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'A+^4', label: '', hz: 456.18, cents: 962.5, degrees: 221.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'A#v4', label: '', hz: 462.82, cents: 987.5, degrees: 273.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Bdv4', label: '', hz: 476.38, cents: 1037.5, degrees: 18.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'Bd^4', label: '', hz: 483.31, cents: 1062.5, degrees: 71.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'B♮^4/Cb^4', label: '', hz: 497.47, cents: 1112.5, degrees: 176.25, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'B+v4/Cdv4', label: '', hz: 504.71, cents: 1137.5, degrees: 228.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },
  { name: 'B#v4/C♮v4', label: '', hz: 519.50, cents: 1187.5, degrees: 333.75, category: 'sixteenthtone-96EDO', textColor: 'white', backgroundColor: 'magenta' },

  { name: '//D4', label: '', hz: 300.53, cents: 240, degrees: 144, category: 'diesis-5EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\F4', label: '', hz: 345.22, cents: 480, degrees: 288, category: 'diesis-5EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '/G4', label: '', hz: 396.56, cents: 720, degrees: 72, category: 'diesis-5EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\\\A#4', label: '', hz: 455.52, cents: 960, degrees: 216, category: 'diesis-5EDO', textColor: 'black', backgroundColor: 'blue' },
  
  { name: '/Db4', label: '', hz: 280.41, cents: 120, degrees: 252, category: 'diesis-10EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\\\E4', label: '', hz: 322.10, cents: 360, degrees: 36, category: 'diesis-10EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '//Ab4', label: '', hz: 425.02, cents: 840, degrees: 324, category: 'diesis-10EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\B4', label: '', hz: 487.72, cents: 1080, degrees: 108, category: 'diesis-10EDO', textColor: 'white', backgroundColor: 'blue' },

  { name: '\\C#4', label: '', hz: 274.00, cents: 80, degrees: 168, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\\\D4', label: '', hz: 286.96, cents: 160, degrees: 336, category: 'diesis-15EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '/Eb4', label: '', hz: 314.75, cents: 320, degrees: 312, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\\\F#4', label: '', hz: 361.55, cents: 560, degrees: 156, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '//Gb4', label: '', hz: 378.65, cents: 640, degrees: 264, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '\\A4', label: '', hz: 434.95, cents: 880, degrees: 48, category: 'diesis-15EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '//Bb4', label: '', hz: 476.58, cents: 1040, degrees: 24, category: 'diesis-15EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '/B4', label: '', hz: 499.11, cents: 1120, degrees: 192, category: 'diesis-15EDO', textColor: 'white', backgroundColor: 'blue' },

  { name: '//C4', label: '', hz: 267.75, cents: 40, degrees: 84, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\D#4', label: '', hz: 307.56, cents: 280, degrees: 228, category: 'diesis-30EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '//E4', label: '', hz: 337.34, cents: 440, degrees: 204, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '/F4', label: '', hz: 353.29, cents: 520, degrees: 12, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\G4', label: '', hz: 387.50, cents: 680, degrees: 348, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\\\G#4', label: '', hz: 405.83, cents: 760, degrees: 96, category: 'diesis-30EDO', textColor: 'black', backgroundColor: 'blue' },
  { name: '/A4', label: '', hz: 445.12, cents: 920, degrees: 132, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },
  { name: '\\\\C4', label: '', hz: 510.78, cents: 1160, degrees: 276, category: 'diesis-30EDO', textColor: 'white', backgroundColor: 'blue' },

  { name: '', label: '', hz: 288.86, cents: 171.43, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 318.93, cents: 342.86, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 352.13, cents: 514.29, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 388.78, cents: 685.71, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 429.25, cents: 857.14, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 473.93, cents: 1028.57, category: 'bohlen-pierce-7EDO', textColor: 'white', backgroundColor: 'chartreuse' },

  { name: '', label: 'C-hexaseptisharp', hz: 274.91, cents: 85.71, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 303.52, cents: 257.14, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 335.12, cents: 428.57, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 408.51, cents: 771.43, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 451.04, cents: 942.86, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 497.98, cents: 1114.29, category: 'bohlen-pierce-14EDO', textColor: 'white', backgroundColor: 'chartreuse' },

  { name: '', label: 'C-tetraseptisharp', hz: 270.41, cents: 57.14, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 279.48, cents: 114.29, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 298.56, cents: 228.57, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 308.58, cents: 285.71, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 340.69, cents: 457.14, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 363.94, cents: 571.43, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 376.16, cents: 628.57, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 401.83, cents: 742.86, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 443.65, cents: 914.29, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 458.54, cents: 971.43, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 489.83, cents: 1085.71, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 506.27, cents: 1142.86, category: 'bohlen-pierce-21EDO', textColor: 'white', backgroundColor: 'chartreuse' },

  { name: '', label: 'C-diseptisharp', hz: 265.98, cents: 28.57, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 284.13, cents: 142.86, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 313.71, cents: 314.29, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 324.24, cents: 371.43, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 346.36, cents: 485.71, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 357.99, cents: 542.86, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 382.42, cents: 657.14, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 395.25, cents: 714.29, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 422.22, cents: 828.57, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 436.39, cents: 885.71, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 481.82, cents: 1057.14, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  { name: '', label: '', hz: 514.70, cents: 1171.43, category: 'bohlen-pierce-42EDO', textColor: 'white', backgroundColor: 'chartreuse' },
  
  { name: 'C#*4', label: '', hz: 282.52, cents: 133, category: 'Limman-9EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'D*4', label: 'D-thirdflat', hz: 305.08, cents: 266, category: 'Limman-9EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'F*4', label: 'F-thirdsharp', hz: 355.95, cents: 533, category: 'Limman-9EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Gb*4', label: '', hz: 384.38, cents: 666, category: 'Limman-9EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'A*4', label: 'A-thirdsharp', hz: 448.48, cents: 933, category: 'Limman-9EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Bb*4', label: '', hz: 484.29, cents: 1066, category: 'Limman-9EDO', textColor: 'black', backgroundColor: 'orange' },

  { name: 'C*4', label: 'C-thirdflat', hz: 271.80, cents: 66, category: 'Limman-18EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'D#*4', label: '', hz: 317.12, cents: 333, category: 'Limman-18EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'E*4', label: 'E-thirdflat', hz: 342.44, cents: 466, category: 'Limman-18EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'G*4', label: 'G-thirdsharp', hz: 399.55, cents: 733, category: 'Limman-18EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Ab*4', label: '', hz: 431.45, cents: 866, category: 'Limman-18EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'B*4', label: 'B-thirdsharp', hz: 503.40, cents: 1133, category: 'Limman-18EDO', textColor: 'white', backgroundColor: 'orange' },

  { name: '', label: '', hz: 268.43, cents: 44.44, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 275.41, cents: 88.89, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 289.92, cents: 177.78, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 297.46, cents: 222.22, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 313.14, cents: 311.11, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 321.28, cents: 355.56, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 338.21, cents: 444.44, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 347.0, cents: 488.89, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 365.28, cents: 577.78, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 374.78, cents: 622.22, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 394.53, cents: 711.11, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 404.79, cents: 755.56, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 426.11, cents: 844.44, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 437.19, cents: 888.89, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 460.23, cents: 977.78, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 472.19, cents: 1022.22, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 497.07, cents: 1111.11, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 510.0, cents: 1155.56, category: 'Limman-27EDO', textColor: 'white', backgroundColor: 'orange' },

  { name: 'C*4', label: 'C-thirdsharp', hz: 266.66, cents: 33, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Db*4', label: '', hz: 287.96, cents: 166, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'D*4', label: 'D-thirdsharp', hz: 299.32, cents: 233, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'Eb*4', label: '', hz: 323.22, cents: 366, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'E*4', label: 'E-thirdsharp', hz: 335.98, cents: 433, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'F*4', label: 'F-thirdflat', hz: 362.80, cents: 566, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'F#*4', label: '', hz: 377.12, cents: 633, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'G*4', label: 'G-thirdflat', hz: 407.23, cents: 766, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'G#*4', label: '', hz: 423.30, cents: 833, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'A*4', label: 'A-thirdflat', hz: 457.11, cents: 966, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: 'A#*4', label: '', hz: 475.12, cents: 1033, category: 'Limman-36EDO', textColor: 'black', backgroundColor: 'orange' },
  { name: 'B*4', label: 'B-thirdflat', hz: 513.08, cents: 1166, category: 'Limman-36EDO', textColor: 'white', backgroundColor: 'orange' },

  { name: '', label: '', hz: 265.01, cents: 22.22, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 278.97, cents: 111.11, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 286.23, cents: 155.56, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 301.31, cents: 244.44, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 309.14, cents: 288.89, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 325.43, cents: 377.78, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 333.89, cents: 422.22, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 351.48, cents: 511.11, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 360.62, cents: 555.56, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 379.62, cents: 644.44, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 389.49, cents: 688.89, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 410.01, cents: 777.78, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 420.68, cents: 822.22, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 442.84, cents: 911.11, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 454.36, cents: 955.56, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 478.29, cents: 1044.44, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 490.73, cents: 1088.89, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
  { name: '', label: '', hz: 516.59, cents: 1177.78, category: 'Limman-54EDO', textColor: 'white', backgroundColor: 'orange' },
];
